### ISSUE TITLE
How can I connect to a remote beanstalkd instance?

### ISSUE THREAD

**Issue by pkaeding** [tyba/beanstool#2]
https://github.com/tyba/beanstool/blob/master/cli/command.go#L14 makes it look like this might be possible, but the usage message doesn't give any hints.

Can I use beanstool to manage a remote beanstalk instance?

Thanks!

**Comment by mcuadros** [comment]
Of course just use `-h` arg and your host

**Comment by pkaeding** [comment]
Ahh, thanks. It seems `-h` conflicts with the usage message (aka `--help`), but `--host=my.beanstalk.host:11300` seems to work.

**Comment by bonswouar** [comment]
Just in case someone encounter the problem I just had : the `--host` option has to be after the command name, otherwise it throws `unknown flag 'host'`.
