### ISSUE TITLE
Sorting output of `stats`

### ISSUE THREAD

**Issue by hamstu** [tyba/beanstool#4]
Would be nice to be able to sort the output of the `beanstool stats` command, I'm using the linux `watch` command with beanstool and the ordering of the tubes changes from run to run.

In the meantime I've solved it by piping beanstool through a simple python script (in case anyone else wants this:)

```
#!/usr/bin/env python

import sys

lines = sys.stdin.readlines()
final = []

if len(lines):
	head = 	lines[:3]
	foot = lines[-1:]
	body = lines[3:-1]
	body.sort()
	
	final = head + body + foot

	for line in final:
		print line,
```

**Comment by eltone** [comment]
@hamstu that script helped me out thanks!

**Comment by mcuadros** [comment]
done, thanks for the feedback.

now all the tubes are sorted by names, except default that is printed always the first.

**Comment by mikegleasonjr** [comment]
Thanks for the work! can you push a release for this one?
